import { defineConfig } from "./src/config/define-config";

export default defineConfig({
	header: `# Changelog

This changelog is generated by fork-version on each push to the main branch.
`,
	types: [
		{ type: "feat", section: "Features" },
		{ type: "fix", section: "Bug Fixes" },
		{ type: "refactor", section: "Refactor" },
		{ type: "docs", section: "Docs" },
		{ type: "chore", section: "Chore" },
		{ type: "style", section: "Style", hidden: true },
		{ type: "perf", section: "Perf", hidden: true },
		{ type: "test", section: "Test", hidden: true },
	],
});
