name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          registry-url: "https://registry.npmjs.org"
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm build

      - name: Publish NPM Package
        run: |
          npm install -g npm@latest
          npm publish

      - name: Publish JSR Package
        run: |
          npx jsr publish --allow-slow-types

      - name: Update Summary
        run: |
          version=$(node .\dist\cli.js inspect-version)
          echo "## Released version: $version" >> $GITHUB_STEP_SUMMARY
