name: Test Pull Request

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: {}

jobs:
  test_node:
    strategy:
      matrix:
        node: [18, 20]
        os: [ubuntu-latest, windows-latest]

    name: Test ${{ matrix.os }} on node v${{ matrix.node }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Run Typecheck
        run: |
          pnpm typecheck

      - name: Run Lint Check
        run: |
          pnpm lint:check

      - name: Run Tests
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          pnpm test:ci

  test_bun:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Test ${{ matrix.os }} on bun
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 8
          run_install: false
          standalone: true

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Run Typecheck
        run: |
          bun run typecheck

      - name: Run Lint Check
        run: |
          bun run lint:check

      - name: Run Tests
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          bun run test:ci
