name: Test Pull Request

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  test_node:
    strategy:
      matrix:
        include:
          - node: 20
            os: ubuntu-latest
          - node: 22
            os: windows-latest

    name: Test Node.js v${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Run Typecheck
        run: |
          pnpm typecheck

      - name: Run Lint Check
        run: |
          pnpm lint:check

      - name: Run Tests
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          pnpm test:ci

      - name: Report Coverage
        if: matrix.node == 20 && matrix.os == 'ubuntu-latest' && github.event_name == 'pull_request' && always()
        uses:  davelosert/vitest-coverage-report-action@v2
